[project]
name = "oetils"
version = "0.2.12"
description = "A collection of useful functions and classes"
authors = [{ name = "Onno Eberhard", email = "onnoeberhard@gmail.com" }]
requires-python = ">=3.9"
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "numpy",
    "matplotlib",
    "scienceplots",
    "tueplots",
    "scipy",
    "jax",
    "tqdm",
    "cluster-utils",
    "al-smart-settings",
    "scikit-learn>=1.6.1",
]

[tool.uv.sources]
cluster-utils = { git = "https://github.com/martius-lab/cluster_utils" }
al-smart-settings = { git = "https://github.com/martius-lab/smart-settings" }

[project.urls]
Repository = "https://github.com/onnoeberhard/oetils"

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
]

[tool.uv.build-backend]
module-name = ["oetils"]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
